# https://docs.netlify.com/configure-builds/file-based-configuration
[build]
command = "yarn build"
publish = ".next"

[build.environment]
NODE_VERSION = "20"
NEXT_PUBLIC_GA_ID = "G-50LPRQPF4H"
NEXT_PUBLIC_GH_CLIENT_ID = "89586b42f4bb2b598272"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "https://mizyind.netlify.app"
to = "https://mizyind.dev"
force = true

[functions]
included_files = [
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/router-context*",
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
]
