# https://docs.netlify.com/configure-builds/file-based-configuration
[build]
command = "yarn build"
publish = ".next"

[build.environment]
NODE_VERSION = "16"
NEXT_PUBLIC_GA_ID = "G-50LPRQPF4H"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "https://mizyind.netlify.app"
to = "https://mizyind.dev"
force = true
